import type { PolicyCategory } from "@repo/schema/policy";
import type { Benefit, BenefitFilter, FinancialTip, SavingTip } from "./types";

/**
 * 필터 칩. `category`는 서버 `/api/policies`의 `category` 쿼리로 그대로 나가는 값이고,
 * 목록을 좁히지 않는 "전체"만 null이다. 저장 목록은 칩이 아니라 `/benefits/saved`다.
 */
export const BENEFIT_FILTERS: readonly {
  value: BenefitFilter;
  label: string;
  category: PolicyCategory | null;
}[] = [
  { value: "all", label: "전체", category: null },
  { value: "finance", label: "금융", category: "금융" },
  { value: "housing", label: "주거", category: "주거" },
  { value: "welfare", label: "복지", category: "복지" },
  { value: "education", label: "교육", category: "교육" },
];

/**
 * 정적 정책 데이터 — UT 대응 가안(디자인 미확정). 공식 URL은 2026-07-21 기준으로 확인했다.
 * 조건·금액 등 상세는 카드에 싣지 않고 공식 페이지로 바로 보낸다. 출시 전 URL 재검증 필요.
 */
export const BENEFITS = [
  {
    id: "youth-future-savings",
    category: "savings",
    title: "청년미래적금",
    summary: "3년 저축하면 소득·근로 형태에 따라 정부기여금을 더해줘요.",
    condition: "만 19~34세 · 소득 요건 확인",
    officialUrl: "https://fill4young.kinfa.or.kr/",
  },
  {
    id: "youth-tomorrow-savings",
    category: "savings",
    title: "청년내일저축계좌",
    summary: "매월 저축하면 정부가 일정 금액을 함께 적립해줘요.",
    condition: "만 19~34세 · 근로·소득 요건",
    officialUrl:
      "https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do?wlfareInfoId=WLF00000060&wlfareInfoReldBztpCd=01",
  },
  {
    id: "youth-housing-dream",
    category: "savings",
    title: "청년 주택드림 청약통장",
    summary: "청약 기능에 우대 금리까지 챙기는 청년 전용 통장이에요.",
    condition: "청년·무주택 등 가입 요건",
    officialUrl: "https://nhuf.molit.go.kr/FP/FP07/FP0701/FP07010301.jsp",
  },
  {
    id: "isa",
    category: "savings",
    title: "ISA(개인종합자산관리계좌)",
    summary: "예금·펀드를 한 계좌에서 굴리고 세제 혜택을 받아요.",
    condition: "국내 거주자 누구나",
    officialUrl: "https://isa.kofia.or.kr/",
  },
  {
    id: "youth-monthly-rent",
    category: "housing",
    title: "청년월세 지원",
    summary: "청년 월세를 일정 기간 지원해 주거비 부담을 줄여줘요.",
    condition: "청년 · 소득·거주 요건",
    officialUrl:
      "https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do?wlfareInfoId=WLF00004661&wlfareInfoReldBztpCd=01",
  },
  {
    id: "youth-jeonse-loan",
    category: "housing",
    title: "청년 버팀목 전세대출",
    summary: "청년 대상 저금리 전세자금 대출이에요.",
    condition: "청년 · 소득·보증금 한도",
    officialUrl: "https://nhuf.molit.go.kr/FP/FP05/FP0502/FP05020301.jsp",
  },
  {
    id: "deposit-return-guarantee",
    category: "housing",
    title: "전세보증금 반환보증 보증료 지원",
    summary: "반환보증 가입 시 내는 보증료 일부를 돌려줘요.",
    condition: "전세 세입자 · 소득 요건",
    officialUrl: "https://www.khug.or.kr/jeonse/web/s05/s050601.jsp",
  },
  {
    id: "k-pass",
    category: "living",
    title: "K-패스",
    summary: "대중교통 이용액 일부를 다음 달에 환급받아요.",
    condition: "대중교통 이용자 · 가입 필요",
    officialUrl: "https://korea-pass.kr/info/intro.do",
  },
  {
    id: "climate-card",
    category: "living",
    title: "기후동행카드",
    summary: "정액권 하나로 서울 대중교통을 무제한 이용해요.",
    condition: "서울 대중교통 이용자",
    officialUrl: "https://news.seoul.go.kr/traffic/archives/510963",
  },
  {
    id: "nonghal-voucher",
    category: "living",
    title: "농할상품권",
    summary: "농축산물 구매 시 할인받는 상품권이에요.",
    condition: "전 국민 · 판매처 확인",
    officialUrl: "https://www.mafra.go.kr/bbs/home/796/576815/artclView.do",
  },
  {
    id: "onnuri-voucher",
    category: "living",
    title: "온누리상품권",
    summary: "전통시장에서 할인가로 쓰는 상품권이에요.",
    condition: "전 국민 · 가맹점 확인",
    officialUrl: "https://onnurigift.or.kr/",
  },
  {
    id: "energy-voucher",
    category: "living",
    title: "에너지바우처",
    summary: "냉난방 등 에너지 비용을 지원받아요.",
    condition: "취약계층 · 소득·세대 요건",
    officialUrl: "https://www.energyv.or.kr/",
  },
  {
    id: "culture-nuri-card",
    category: "living",
    title: "문화누리카드",
    summary: "문화·여행·체육에 쓰는 통합문화이용권이에요.",
    condition: "기초수급·차상위 계층",
    officialUrl: "https://www.mnuri.kr/munhwa/introduceNuri.do",
  },
  {
    id: "earned-income-tax-credit",
    category: "tax",
    title: "근로장려금",
    summary: "일하는 저소득 가구에 소득에 따라 장려금을 지급해요.",
    condition: "저소득 근로·사업 가구",
    officialUrl: "https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7784&mi=2450",
  },
  {
    id: "sme-youth-tax-reduction",
    category: "tax",
    title: "중소기업 취업 청년 소득세 감면",
    summary: "중소기업에 취업한 청년의 소득세를 일정 기간 감면해줘요.",
    condition: "중소기업 취업 청년",
    officialUrl: "https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=239023",
  },
  {
    id: "monthly-rent-tax-credit",
    category: "tax",
    title: "월세 세액공제",
    summary: "무주택 근로자가 낸 월세 일부를 세액공제로 돌려받아요.",
    condition: "무주택 근로자 · 소득 요건",
    officialUrl: "https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=239025&mi=40634",
  },
] satisfies Benefit[];

export const FINANCIAL_TIPS = [
  {
    id: "youth-future-savings",
    category: "정부 정책",
    title: "20대 필수, 청년 미래적금 가입조건 정리",
    summary: "최대 2,255만원 수령 가능",
  },
  {
    id: "delivery-saving",
    category: "절약 꿀팁",
    title: "배달비만 줄여도 쏠쏠해요",
    summary: "1인 가구 식비 절약법",
  },
  {
    id: "subscription-saving",
    category: "고정비 관리",
    title: "안 쓰는 구독은 이번 달에 정리해요",
    summary: "월 1만원부터 모아보기",
  },
] satisfies readonly FinancialTip[];

/**
 * 콘텐츠 팀이 수집·검수한 절약 팁. API로 받지 않는 이유는 노션의 편집 데이터를 즉시 반영하는
 * 이번 범위에서 인증·캐시·장애 경로를 새로 만들지 않기 위해서다. URL이 없는 간식 항목은
 * 사용자에게 열 수 없는 카드를 만들지 않도록 제외했다.
 */
export const SAVING_TIPS = [
  {
    id: "home-cooking-recipe",
    category: "식비",
    selection: "배달음식",
    ragText: "배달 메뉴 대신 집에서 직접 만드는 레시피 찾아보기",
    title: "집밥 레시피 활용팁",
    url: "https://www.youtube.com/watch?v=nZw2A76aZaw",
  },
  {
    id: "meal-prep",
    category: "식비",
    selection: "외식",
    ragText: "밀프랩으로 식단 미리 만들어 두기",
    title: "밀프렙 식단관리팁",
    url: "https://www.youtube.com/watch?v=ke5muhJxFWo",
  },
  {
    id: "grocery-shopping",
    category: "식비",
    selection: "외식",
    ragText: "저렴하게 장보기 스킬로 식비 아끼기",
    title: "저렴한 장보기 스킬",
    url: "https://www.youtube.com/watch?v=H0vlG-mHk7g",
  },
  {
    id: "cafe-gifticon",
    category: "식비",
    selection: "카페",
    ragText: "카페별 할인된 기프티콘 미리 챙기기",
    title: "커피 기프티콘 할인구매팁",
    url: "https://blog.naver.com/namakemori/224231608416",
  },
  {
    id: "convenience-store-event",
    category: "식비",
    selection: "편의점",
    ragText: "GS25 편의점 8월 행사 카카오페이 토스 할인 혜택 챙기기",
    title: "GS25 편의점 8월 행사 및 혜택",
    url: "https://blog.naver.com/damoahousing/224366685453",
  },
  {
    id: "convenience-store-payback",
    category: "식비",
    selection: "편의점",
    ragText: "편의점 페이백 이벤트 혜택 챙기기",
    title: "8월 네이버페이 편의점 페이백 이벤트 혜택 총정리",
    url: "https://blog.naver.com/y0ng00322/224372833847",
  },
  {
    id: "convenience-store-card",
    category: "식비",
    selection: "편의점",
    ragText: "편의점 할인 카드 혜택으로 절약하기",
    title: "CU·GS25·세븐일레븐 할인 카드 총정리 (2026)",
    url: "https://blog.naver.com/playplanet-/224367726782",
  },
  {
    id: "convenience-store-subscription",
    category: "식비",
    selection: "편의점",
    ragText: "GS25 및 CU 편의점 앱 구독 서비스를 이용해 간편식과 커피 할인 혜택을 챙기기",
    title: "GS25 및 CU 편의점 통신사 멤버십 중복 및 마감 할인 앱 활용법",
    url: "https://blog.naver.com/greenbook23/224367450635",
  },
  {
    id: "karrot-market",
    category: "생활",
    selection: "의류",
    ragText: "당근마켓서 감가 큰 전자기기 중고구매, 안 쓰는 옷은 판매해 현금화",
    title: "당근마켓 중고활용팁",
    url: "https://onsehub2026.blogspot.com/2026/03/14.html",
  },
  {
    id: "clothing-resale",
    category: "생활",
    selection: "의류",
    ragText: "고가브랜드는 위탁판매, 중가는 당근마켓, 저가는 리클로 일괄처분",
    title: "가격대별 중고처분팁",
    url: "https://livedailycare.com/minimalist-closet-20260503/",
  },
  {
    id: "musinsa-coupon",
    category: "생활",
    selection: "의류",
    ragText: "무신사 등급쿠폰, 시즌세일, 아울렛·중고를 함께 활용하기",
    title: "무신사 쿠폰중복 활용팁",
    url: "https://echeveau.net/musinsa-complete-guide-hub/",
  },
  {
    id: "daiso-skincare",
    category: "생활",
    selection: "화장품",
    ragText: "다이소 기초템 토너와 앰플 활용하기",
    title: "다이소 화장품 꿀템 모음 2026",
    url: "https://www.youtube.com/watch?v=kLn8Kg9Fx0g",
  },
  {
    id: "oliveyoung-rewardings",
    category: "생활",
    selection: "화장품",
    ragText: "리워딩스로 올리브영 리뷰 체험단 참여하기",
    title: "올리브영 제품 페이백 받는 리워딩스 활용팁",
    url: "https://blog.naver.com/by_lami_/224323780483",
  },
  {
    id: "empty-cosmetic-containers",
    category: "생활",
    selection: "화장품",
    ragText: "화장품 공병을 매장에 가져가 재활용 포인트나 할인 혜택 받기",
    title: "화장품 공병 수거 및 재활용 포인트 적립 꿀팁 3가지",
    url: "https://blog.naver.com/whirlpoolbath/224204100148",
  },
  {
    id: "daiso-makeup",
    category: "생활",
    selection: "화장품",
    ragText: "다이소 화장품 PDRN, 리들샷, 화장 전 베이스 활용하기",
    title: "다이소 화장품 추천 2026 품절템",
    url: "https://byuppo.com/2026-daiso-beauty-top5/",
  },
  {
    id: "daiso-shopping",
    category: "생활",
    selection: "생활용품",
    ragText: "다이소에서 손해 보기 쉬운 품목을 피하고 정기배송·매장픽업 활용하기",
    title: "다이소 손해품목 피하기",
    url: "https://dasaja.co.kr/saja_guide/15",
  },
  {
    id: "daiso-storage",
    category: "생활",
    selection: "생활용품",
    ragText: "다이소템 수납정리 팁으로 별도 수납용품 구매 없이 정돈하기",
    title: "다이소 수납정리 꿀팁",
    url: "https://www.youtube.com/watch?v=QAm3iCpih2s",
  },
  {
    id: "fallcent-price-tracker",
    category: "생활",
    selection: "생활용품",
    ragText: "폴센트 앱으로 쿠팡 가격변동을 추적해 최저가 타이밍에 구매하기",
    title: "폴센트 최저가 추적팁",
    url: "https://fallcent.com/",
  },
  {
    id: "beauty-model",
    category: "생활",
    selection: "미용",
    ragText: "속눈썹펌·헤어·네일 모델과 체험단을 활용해 꾸밈비 아끼기",
    title: "거지대학생의 꾸밈비 절약 꿀팁 대공개!!",
    url: "https://blog.naver.com/godjoo27/224354310092",
  },
  {
    id: "hair-model",
    category: "생활",
    selection: "미용",
    ragText: "헤어모델 협찬 활용하기",
    title: "헤어모델 협찬 할인팁",
    url: "https://www.hankyung.com/article/2025012230647",
  },
  {
    id: "beauty-experience-group",
    category: "생활",
    selection: "미용",
    ragText: "체험단 플랫폼에서 뷰티·미용 시술 무료체험 신청하기",
    title: "체험단 무료뷰티 혜택",
    url: "https://www.revu.net/",
  },
  {
    id: "community-center-class",
    category: "취미",
    selection: "수업&클래스",
    ragText: "주민자치센터 문화·교양 강좌 활용하기",
    title: "주민센터 숨은 복지 혜택 활용 꿀팁",
    url: "https://blog.naver.com/coolmasinser/224353887451",
  },
  {
    id: "leisure-discount-card",
    category: "취미",
    selection: "공연&전시&티켓",
    ragText: "영화·전시회·공연을 자주 다니면 여가 생활 할인 카드 이용하기",
    title: "여가생활 할인카드 추천 순위 비교 (feat. 최대 할인 받는 법)",
    url: "https://blog.naver.com/2hmii/224372836055",
  },
  {
    id: "regional-performance-discount",
    category: "취미",
    selection: "공연&전시&티켓",
    ragText: "문체부 비수도권 공연 관람료 할인권 활용하기",
    title: "9월부터 공연 관람료 1만 원 할인 받는팀",
    url: "https://blog.naver.com/mcstkorea/224469832643",
  },
  {
    id: "youth-culture-pass",
    category: "취미",
    selection: "공연&전시&티켓",
    ragText: "청년문화예술패스로 만 19세 청년의 공연·전시 관람 지원받기",
    title: "청년문화예술패스 혜택",
    url: "https://youthculturepass.or.kr/",
  },
  {
    id: "sac-same-day-ticket",
    category: "취미",
    selection: "공연&전시&티켓",
    ragText: "예술의전당 당일예매 할인티켓 활용하기",
    title: "예술의전당 당일할인팁",
    url: "https://www.sac.or.kr/site/main/show/show_list_ticket",
  },
  {
    id: "culture-day-discount",
    category: "취미",
    selection: "공연&전시&티켓",
    ragText: "문화가 있는 날과 정부 할인권을 중첩해 공연 관람비 아끼기",
    title: "문화가있는날 중첩할인팁",
    url: "https://dasaja.co.kr/saja_guide/197",
  },
  {
    id: "movie-morning-membership",
    category: "취미",
    selection: "공연&전시&티켓",
    ragText: "영화 조조할인과 통신사 멤버십 할인을 중복 활용하기",
    title: "영화 조조+멤버십 할인팁",
    url: "https://www.ajd.co.kr/contents/basic-tip/detail/%EC%98%81%ED%99%94_%EC%A1%B0%EC%A1%B0%ED%95%A0%EC%9D%B8_%EC%8B%9C%EA%B0%84_%EB%AF%B8%EB%A6%AC_%EC%B0%BE%EC%95%84%EB%B3%B4%EA%B8%B0%EB%A9%94%EA%B0%80%EB%B0%95%EC%8A%A4,_cgv,_%EB%A1%AF%EB%8D%B0%EC%8B%9C%EB%84%A4%EB%A7%88-70007",
  },
] satisfies readonly SavingTip[];
